### ISSUE TITLE
Please allow users to specify fonts

### ISSUE THREAD

**Issue by kth-tw** [curvednebula/api-docbaker-js#1]
My swagger.json include some Chinese word. It generate pdf like here
<img width="431" alt="image" src="https://github.com/curvednebula/apibake-js/assets/88102592/42fde3e5-24b1-416f-bc8f-635202663d68">
If I change [here](https://github.com/curvednebula/apibake-js/blob/master/src/pdf-writer.ts#L72)
from
```typescript
'Helvetica'
```
to
```typescript
`${process.env.HOME}/Library/Fonts/NotoSansMonoCJKtc-Regular.otf`
```
it can show Chinese successfully.

Can you add a cli argument to set font?

**Comment by curvednebula** [comment]
Thanks! Yes, font configuration will be added to apibake-config.json. See --export-config option.

**Comment by kth-tw** [comment]
Another question:

I have  `summary` and `description` in json, but I can't find in generated pdf document.

**Comment by curvednebula** [comment]
I think descriptions of exact HTTP responses (200, 300, 400, etc.) are displayed. But not the overall description of the REST API endpoint itself. Let me take a look.

**Comment by curvednebula** [comment]
API summary and description added in 0.1.19 - let me know if this fixes your problem. Custom fonts will be added a bit later - need to come up with proper config structure for that.

**Comment by kth-tw** [comment]
Thanks for upgrading.

There is summary and description now.

<img width="476" alt="image" src="https://github.com/curvednebula/apibake-js/assets/88102592/2ad15c76-e2c4-4186-9f2a-7c0a844bf489">

**Comment by curvednebula** [comment]
Font configuration is added in 0.1.21 - check readme for more details.

**Comment by kth-tw** [comment]
Thanks for upgrading. It work.
