### ISSUE TITLE
Add option to disable page numbers

### ISSUE THREAD

**Issue by 0x0dr1y** [curvednebula/api-docbaker-js#4]
Hey,

it would be great if there is an option to disable the page number generation. Looking at the code this should be quite simple.

What are your thoughts on this?

**Comment by curvednebula** [comment]
Yes, I think this should be easy to do. I'll check. I'm curious why is it important to hide page numbers?

**Comment by 0x0dr1y** [comment]
> Yes, I think this should be easy to do. I'll check. I'm curious why is it important to hide page numbers?

Cool, thanks! Let me know if you need any help.

Use case: The resulting pdf is getting merged with other independent pdfs in the end. After merging the site numbers are programatically added, thus disabling page numbers is important as they're simply inaccurate in such cases.

**Comment by curvednebula** [comment]
@MrDeerly Please check the latest version. Now you can specify the following option to disable page numbers:
--footer ""

**Comment by 0x0dr1y** [comment]
@curvednebula Thanks alot for your fast efforts! I can confirm the new version works as intended. Again, thanks for the great project :+1:

**Comment by curvednebula** [comment]
Thanks, I'm glad it helped! Closing the issue.

**Comment by curvednebula** [comment]
Thanks!
