### ISSUE TITLE
[FEAT] Add support for information section

### ISSUE THREAD

**Issue by Defkon1** [curvednebula/api-docbaker-js#5]
It would be great adding the parsing of the information from _info_ section (when available) on the frontpage of the PDF:

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "My API title",
    "description": "My API description",
    "termsOfService": "https://www...",
    "contact": {
      "name": "Defkon1",
      "url": "https://www.github.com/defkon1",
      "email": "..."
    },
    "license": {
      "name": "CC-BY 4.0",
      "url": "https://creativecommons.org/licenses/by/4.0/legalcode"
    },
    "version": "1.0.0",
    "x-summary": "...",
    "x-api-id": "..."
  }
```

Something similar to RapiPDF, just to give an example:

![image](https://github.com/curvednebula/apibake-js/assets/686298/3b3d2b45-eec7-4095-be4e-fa0fa4e06d94)

**Comment by Defkon1** [comment]
Any news @curvednebula ?

**Comment by Defkon1** [comment]
bump

**Comment by curvednebula** [comment]
Hello, thank you for the Pull Request, I will take a look and merge it as soon as possible.

**Comment by curvednebula** [comment]
While please note that apibake can combine multiple json/yaml files into a single PDF (if you specify multiple files as input or a folder with multiple files). In this case it isn't clear how to combine details from multiple json/yamls into a single header.

**Comment by Defkon1** [comment]
> While please note that apibake can combine multiple json/yaml files into a single PDF (if you specify multiple files as input or a folder with multiple files). In this case it isn't clear how to combine details from multiple json/yamls into a single header.

sorry for the late reply; each header is processed separately, and not combined in a single page (I'm not sure whether the "combined" header could be useful)

**Comment by curvednebula** [comment]
@Defkon1 Right, I've realized that when I reviewed your code. Thanks for your contribution!
